### ISSUE TITLE
Cloud Files objects with spaces get broken temporary URLs

### ISSUE THREAD

**Issue by willemo** [rackspace/php-opencloud#412] opened 2014-10-07 13:44 UTC
The implemented fix to issue #106 causes generated temporary urls for objects with spaces in their names to be broken.
When I changed the current code in DataObject.php (line 389):
```php
$url = $this->getUrl();
$urlPath = urldecode($url->getPath());
```
To:
```php
$url = $this->getUrl();
$urlPath = $url->getPath();
```
Temporary URLs work fine again for objects with spaces in their names. Although this might cause issues with objects which have not url-safe characters in their names.

**Comment by jamiehannaford** [comment] 2015-01-09 10:44
@willemo Is this still an issue for you running the latest version?

**Comment by willemo** [comment] 2015-01-09 10:48
@jamiehannaford I haven't been using the latest version in production yet. So I couldn't tell, sorry!

**Comment by jamiehannaford** [comment] 2015-01-09 10:49
@willemo Okay, no problem. I still can't recreate this problem. Could you send me some sample code and the error codes you're receiving please? If they are sensitive, you can e-mail them to jamie.hannaford@rackspace.com

**Comment by jamiehannaford** [comment] 2015-02-26 15:17
@willemo Hi Willem, I'm going to go ahead and close this since I cannot reproduce. If you're running into any more problems, please feel free to open up another issue. Thanks!

**Closed by jamiehannaford** 2015-02-26 15:17 UTC
Labels: Object Storage

**Comment by willemo** [comment] 2015-02-26 15:18
@jamiehannaford sorry for the long silence, I've not been working on our ObjectStore project for a while. I'll open up this issue if I run into the problem again. Thanks for the effort!
